"""empty message

Revision ID: 9443599b9659
Revises: c3e54619fe20
Create Date: 2020-06-28 20:49:50.812822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9443599b9659'
down_revision = 'c3e54619fe20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('movie_actors',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.add_column('movie', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('country', sa.String(length=70), nullable=True))
    op.add_column('movie', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('movie', sa.Column('fees_in_world', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('poster', sa.LargeBinary(), nullable=True))
    op.add_column('movie', sa.Column('premiere', sa.DateTime(), nullable=True))
    op.add_column('movie', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('movie', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('movie', 'body')
    op.drop_column('movie', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'year')
    op.drop_column('movie', 'tagline')
    op.drop_column('movie', 'premiere')
    op.drop_column('movie', 'poster')
    op.drop_column('movie', 'fees_in_world')
    op.drop_column('movie', 'description')
    op.drop_column('movie', 'country')
    op.drop_column('movie', 'budget')
    op.drop_table('movie_actors')
    op.drop_table('actor')
    # ### end Alembic commands ###
