"""empty message

Revision ID: a391670e4845
Revises: 
Create Date: 2020-06-27 15:26:54.426981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a391670e4845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.add_column('genre', sa.Column('slug', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'genre', ['slug'])
    op.drop_column('genre', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_column('genre', 'slug')
    op.create_table('genres',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='genres_movie_id_fkey')
    )
    # ### end Alembic commands ###
